// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Publish is an autogenerated mock type for the Publish type
type Publish struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event, message
func (_m *Publish) Publish(event string, message string) {
	_m.Called(event, message)
}

// NewPublish creates a new instance of Publish. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublish(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publish {
	mock := &Publish{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
