// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	dto "mlm/dto"

	mock "github.com/stretchr/testify/mock"
)

// Workflow is an autogenerated mock type for the Workflow type
type Workflow struct {
	mock.Mock
}

// AddStep provides a mock function with given fields: name, step
func (_m *Workflow) AddStep(name string, step dto.SagaStep) {
	_m.Called(name, step)
}

// Execute provides a mock function with given fields:
func (_m *Workflow) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkflow creates a new instance of Workflow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflow(t interface {
	mock.TestingT
	Cleanup(func())
}) *Workflow {
	mock := &Workflow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
