basePath: /
definitions:
  dto.NodeCreateRequest:
    properties:
      confirm_password:
        example: "123456"
        type: string
      email:
        example: mehrdad@gmail.com
        type: string
      password:
        example: "123456"
        type: string
      phone_number:
        example: "09120246217"
        type: string
      referral:
        example: L100@2154
        type: string
      username:
        example: mehrdad
        type: string
      wallet_id:
        example: TZJjSqfXwTP5YgjdhLdRV1zqpDwDsgdZZE
        type: string
    type: object
host: localhost:1320
info:
  contact: {}
  description: Server API
  title: Golang
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.NodeCreateRequest'
      produces:
      - application/json
      responses: {}
      summary: node register
swagger: "2.0"
